### ISSUE TITLE
Cannot find module 'Handlebars'

### ISSUE THREAD

**Issue by bizsimon** [4ern/laravel-mix-handlebars#2]
This is running on Linux, not sure if that has anything to do with it.

```
(node:575434) UnhandledPromiseRejectionWarning: Error: Cannot find module 'Handlebars'
Require stack:
- /project/node_modules/laravel-mix-handlebars/render.js
- /project/node_modules/laravel-mix-handlebars/index.js
- /project/webpack.mix.js
- /project/node_modules/laravel-mix/setup/webpack.config.js
- /project/node_modules/webpack-cli/lib/webpack-cli.js
- /project/node_modules/webpack-cli/lib/bootstrap.js
- /project/node_modules/webpack-cli/bin/cli.js
- /project/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at HandlebarTask.precompile (/project/node_modules/laravel-mix-handlebars/render.js:29:27)
    at HandlebarTask.run (/project/node_modules/laravel-mix-handlebars/render.js:12:14)
    at CustomTasksPlugin.runTask (/project/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:38:36)
    at CustomTasksPlugin.runTasks (/project/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:79:21)
    at /project/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:12:18
    at Hook.eval [as callAsync] (eval at create (/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:70:1)
(node:575434) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by bizsimon** [comment]
looks like the issue is in render.js
line 29 and 30
changing to this works. want me to send in a pull request?
```
        this.Handlebars = require('handlebars');
        this.layouts = require('handlebars-layouts');
```
